### PR TITLE
Reorder feat by alphabetical order

### PR DESCRIPTION
**Pull request by jcte02**

### CODE REVIEW

**Comment by brianfeister** [comment]
👍

**Comment by ucffool** [comment]
Shouldn't Fast Draw be moved up in front of Fast Tracker or am I missing something?

**Comment by brianfeister** [comment]
Probably. I'm just at my day job and probably scanned it in too much haste.

**Comment by ucffool** [comment]
I'm going through them now and fixing all alphabetical sorting (used online sorter to sort by name as a double-check). I'll also check boons and banes. Commit soon.

**Comment by jcte02** [comment]
lol I don't know why either it is misplaced. Fixed in #202.

**Comment by ucffool** [comment]
@jcte02 Halted my checks. Here is the full list (there are more currently out of order), since you're already workin' it.
Alternate Form (I - II) 3
Area Manipulation (I - V) 1
Armor Mastery (I - III) 2
Attack Redirection 3
Attack Specialization (I - IX) 3
Attribute Substitution 3
Bane Focus 3
Battlefield Defender 2
Battlefield Punisher - Knockdown 3
Battlefield Punisher - Slowed 3
Battlefield Punisher - Stunned 3
Battlefield Sentinel (I - V) 2
Berserker 3
Boon Access 1
Boon Focus (I - III) 3
Breakfall (I - IX) 1
Brutal Intimidation 1
Climbing 2
Combat Follow-through 2
Combat Momentum 1
Companion (I - III) 3
Craft (I - II) 2
Craft Beneficial or Baleful Item (I - III) 3
Crushing Blow 3
Death Blow (I – III) 3
Deathless Berserker 3
Defensive Reflexes (I - X) 2
Destructive Berserker 3
Diehard 2
Disease Immunity 1
Energy Resistance (I - IV) 2
Entranced Berserker 3
Evasive Footwork 2
Extraordinary Defense (I - V) 2
Extraordinary Focus 3
Extraordinary Healing 3
Fast Draw 2
Fast Tracker 2
Ferocious Minions 2
Fleet of Foot (I – III) 2
Flying 3
Great Leap (I – III) 1
Hallucination - Mass 3
Hallucination 3
Heavy Weapon Master 3
Hospitaler 2
Hunter's Foe (I - IX) 1
Indomitable Endurance (I - IX) 2
Inspiring Champion (I - III) 2
Knowledge (I - III) 2
Lethal Strike (I – IX) 3
Lightning Reflexes (I - V) 1
Marksman (I - III) 1
Martial Focus 3
Master Tracker 1
Mimic 2
Multi-Attack Specialist (I – VI) 3
Multi-Bane Specialist 3
Multi-Target Attack Specialist (I – V) 2
Multi-Target Boon Expert 3
Multi-Target Boon Specialist (I – V) 2
Natural Defense (I - III) 2
Overpowering Strike 2
Potent Bane 3
Reactionary Berserker 2
Reckless Frenzy 3
Resilient 3
Ritual Magic (I - III) 2
Silencing Strike 3
Skill Specialization (I - V) 2
Superior Concentration (I - III) 3
Swimming 1
Tough as Nails (I - II) 2
Two Weapon Brute 3
Two Weapon Defense 2
Unending Charm 3
Untrackable 1
Vicious Strike 2
Wealthy
Well-Rounded 2

**Comment by ucffool** [comment]
Banes is fine, but under **Boons**, Aura and Augury need to be flipped.

**Comment by jcte02** [comment]
Fixed for real in #203

**Pull request merged**
