### PR TITLE
Demoralized Bane

### PR DESCRIPTION
**Pull request by ucffool**

### CODE REVIEW

**Comment by brianfeister** [comment]
Hmmm, why the change? The idea is that demoralization is a mental condition that doesn't require a move action to counter

**Comment by ucffool** [comment]
It's literally the only Bane under this special condition. Furthermore, I was running a game yesterday and when you combine Stunned with Demoralized it's actually harder to shake off (unless you succeed at your Resist roll).
So partially for simplicity.

**Comment by ucffool** [comment]
I'll add that since it is the only one like that, it's easily forgotten that it has this special condition (by the GM). I sure as hell missed it yesterday (along with misinterpreting that it would also effect Resist (which Skysear reminded me wasn't an action, which is also what my 2nd time players assumed as well).

**Comment by brianfeister** [comment]
Oh wait. Resist isn't an action? That's news to me. I thought it was a move action

**Comment by ucffool** [comment]
So I wasn't wrong on that? yay!
I was lamenting that Stunned + Demoralized was brutal against my solo boss NPC because of the Disadvantage on Resist.

Skysear's argument was that Resist being an action would negate the benefit of Potent Bane (Demoralized).

Anyway, this is off-topic (it's in #gm_resources of Discord), since I still think Demoralized should be changed.

**Comment by BuildAndDie** [comment]
Resist is move action, but it was never defined as an MAJOR or MINOR Action, b/c then advantage could be applied to it. And only certain feats are suppose to be able to affect resist rolls.

**Comment by BuildAndDie** [comment]
Resist Roll was not suppose to be defined as an Action Roll for that purpose at least.

Only Potent or Resilent were suppose to be able to affect advantage/disadvantage to resist rolls. Unless that wasn't the case @brianfeister

**Comment by BuildAndDie** [comment]
so we might need to add some clarification in chapter 7 when it talks about "Resist Banes".

Something that mentions these are not action rolls, and only feats may give or advantage/disadvantage to them.

Again, unless that is NOT as intended Brian, and you are suppose to be able to use regular attacks and banes to give disadvantage to resist rolls.

**Comment by BuildAndDie** [comment]
skysear found it:

"These rules apply to both actions performed with an attribute score of zero, as well as non-action rolls (like the d20 used for a Resist roll)."
Found in chapter 2 under Advantage and Disadvantage without attribute dice.

**Comment by brianfeister** [comment]
Ok. So the intent, and yes this is confusing, was that it is an action, but it's NOT an action roll. We can clarify that. "Action rolls" are just the terminology for saying whether or not to add attribute dice, which is the only reason for the distinction. 

In this case, yes, there are multiple places where the action type cost (Minor vs. Move vs. Free ) varies. The Influence attribute has a number of banes that are resisted as a Minor action.

**Comment by ucffool** [comment]
#370 Created for the `Resist` as an **Action** discussion. 

Returning this Pull Request comment thread to the original issue of whether `Demoralized` bane should be **Resist (minor)**

**Comment by brianfeister** [comment]
We can keep the discussion here

**Comment by brianfeister** [comment]
@ucffool I'm not seeing a reason that Demoralized should be changed, but I'll agree that both **Demoralized** and **Provoked** should probably be the same. Other than that, I can't see a reason to force a mental affliction that is very temporary to require a full move action to "convince yourself not to be intimidated / scared, etc." in a similar way to how `Fear` forces you to take a self-destructive action and you get to Resist it at a lower cost.

**Pull request closed without merging**
