### PR TITLE
Remove leftover supernatural occurrences

### PR DESCRIPTION
**Pull request by jcte02**
I'm not sure about all of them, it may needs reviewing.

### CODE REVIEW

**Comment by Elvenoob** [comment]
I'd say, set the Heal and Regeneration boons back to the way they were before, Heal already mentions medicine for the sci-fi version, and in regen, the word supernatural was attached to the Troll example, so just adding a more futuristic example to that one would probably work better.

**Comment by jcte02** [comment]
Regarding the troll in `Absorb Object` it is written
> Extraordinary creatures who are innately magical, such as a nymph, constantly radiate magic.

So I tought to change it here as well.

**Comment by brianfeister** [comment]
Yup, @istabosz is going to review this, some of these aren't quite right but no worries at all. We will look it over and you are absolutely huge help to me.

**Comment by jcte02** [comment]
Rebased and reflected changes on the SRD as well.

**Comment by jcte02** [comment]
Resolved merge conflict

**Comment by brianfeister** [comment]
👍

**Pull request merged**
