### PR TITLE
She/he to they

### PR DESCRIPTION
**Pull request by Cryogenic6891**
She/he changes to 'they' where they make sense

### CODE REVIEW

**Comment by jcte02** [comment]
@Cryogenic6891 Could you also reflect the changes in the SRD file?

**Comment by brianfeister** [comment]
ditto what @jcte02 said, if possible. No pressure, I can add it when I get around to reviewing this.

**Comment by Cryogenic6891** [comment]
alright I merged this one properly, I think hehe

**Comment by jcte02** [comment]
No because it is a System Reference Document, it should report rules only.

**Comment by brianfeister** [comment]
👍

**Pull request merged**
