### PR TITLE
Fixing GitHub Issues

### PR DESCRIPTION
**Pull request by ucffool**
As well as Armor Mastery and Battle Trance updates.

### CODE REVIEW

**Comment by brianfeister** [comment]
👍

**Comment by ucffool** [comment]
so um, should I just not bother with changes or pull requests anymore?

**Comment by brianfeister** [comment]
Huh, why's that? I didn't think I rejected the PR just got distracted and approved it, went to check something and then never came back

**Comment by brianfeister** [comment]
👍

**Pull request merged**
