### PR TITLE
Fix duplicated key

### PR DESCRIPTION
**Pull request by KevinBacas**
Hello people,

I tried to use your yaml files in one of my my projects and the parsing failed due to a "Duplicated key error". It's seems that there is a duplicated "Feat" key in the yaml. 
I fixed it so every parser could parse it without any error or warnings.

I thought you could be interested.

Thank you for your work BTW!

### CODE REVIEW

**Comment by KevinBacas** [comment]
After some research, it seems like this is something that you wanted.
https://github.com/openlegend/core-rules/commit/1f477d242cbf3868786e822e0c956062ff059daf#diff-85246036cc69772fc0128ab9a8fbef1d

I'm not here to blame anyone or so, I just don't want you to introduce a regression in the file :sweat_smile:.
Apparently you only display the second prerequisite on the website. So is the first one necessary?
image

**Comment by brianfeister** [comment]
Definitely a bug on our end that needs fixing, thanks @KevinBacas. When examining the YAML file did you happen to notice if this pattern is used anywhere else or if it's just here? 
```
     tierX:
        Feat:
        - Feat #1
        - Feat #2
```
I was looking and it seems this is the only feat that has a prerequisite of two other feats? If so, we might need to add a new key. We have `MultiAttribute` because we don't know if it's an `OR` type of rule / query or an `AND`. So this is related. `MultiFeat` would mean instead of a list of possible feats that satisfy the prerequisite, it's an `AND` list where all must be met.

**Comment by jcte02** [comment]
Or we could be radical and change the keys to a more simpler approach, so that we avoid introducing new keys for special cases (thus increasing the complexity).
What I have in mind is this (the same applies for attributes).
````yaml
tierX:
  Required:
    Feat:
    - Feat #1
    - Feat #2
  Optional:
    Feat:
    - Feat #3
    - Feat #4
````
`Required` items are chained by `AND`, while `Optional` are chained by `OR`. 

`Optional` is not a good key name but I can't find a more suitable name. What `Optional` should mean is `at least one of the following`. If in English exists a single word that represent this concept I would suggest to swap `Optional` for said word.

This new system allows to code complex query like the one for the `Craft` feat, which has the prerequisite of `Learning 3, OR Knowledge I feat`.
````yaml
tier1:
  Optional:
    Feat:
    - Knowledge I
    Attribute:
    - Learning 3
````

**Comment by jcte02** [comment]
Maybe `OneOf` would be better than `Optional`.

**Comment by brianfeister** [comment]
Yeah definitely an improvement @jcte02

**Comment by brianfeister** [comment]
Good suggestion!

**Comment by brianfeister** [comment]
Keys could be `oneOf` and `all`

**Comment by KevinBacas** [comment]
I only saw a duplication here. After this hotfix, the yaml parser parsed the file successfully.

`oneOf` and `all` are good solutions if you want to express these logical conditions. The keys are clearly obvious to understand in my opinion.

**Comment by jcte02** [comment]
@KevinBacas The problem is that the hotfix is not logically correct. 
Feats listed under the same `Feat` keyare supposed to be in an `or` chain, while here they should be in an `and` chain. Keys under the same `tierX` key are supposed to be in an `and` chain, so there is why they were two `Feat` keys. 
Alas, hash keys are unique. Some parsers throw an error for duplicate keys (like the one you used), while others silently override the value in the hash with the last reference found (so this is why on the site it was displayed only the last feat prerequisite).
We solved this problem for attributes introducing the obsucre `MultiAttribute` key (all attributes listed are in an `and` chain), but since the problem is widespread we are trying to not introduce a new key going instead for a new simpler and more flexible system.
Hope to have shed some light on the matter 😃

**Comment by jcte02** [comment]
@brianfeister What about `all` and `any`, so that the key name matches the query name?

**Comment by ucffool** [comment]
I'm crying on the inside, only because of the work involved in parsing a new structure. 
I noticed this when building the page, but just *fixed* it to match the main site. I should have realized it was an error in layout, but clearly thought it was just something I was doing wrong.
`````
foreach ($feats as $fixfeatsk=>&$fixfeatsv){
	// Fix for wierdness from YML to Array
	if ($fixfeatsv['name'] == 'Multi-Target Boon Expert'){
		$fixfeatsv['prerequisites']['tier1']['Feat'][0] = 'Multi-Target Boon Specialist II';
	}
}
``````
I don't think the structure needs to be changed, as @KevinBacas pointed out, the layout assumes *and* between multiple items (FEAT and ATTRIBUTE or FEAT and FEAT in this case), and OR within (FEAT with two keys), so I think just having this simple fix to the YML solves it.

**Comment by jcte02** [comment]
**NOTE:** `Multi-Target Boon Expert` prerequisite is also wrong in the SRD

**Comment by brianfeister** [comment]
@ucffool you said:

> I don't think the structure needs to be changed, as @KevinBacas pointed out, the layout assumes and between multiple items (Feat and Attribute or Feat and Feat in this case), and OR within (Feat with two keys) unless it's a special key like MultiAttribute, so I think just having this simple fix to the YML solves it.

Unfortunately `Feat` and `Feat` is a duplicate key. What we've discovered on this thread and had pointed out by both @KevinBacas and @jcte02 is that `tier1.Feat[0,1]` coupled with `tier1.Feat[2,3]` does one of two things:

1) It throws an error in the YAML parser
2) It doesn't throw an error and silently fails, which is why things are displaying incorrectly

So, the only real question we need to ask here is whether we're doing

A) 

```
     tierX:
        MultiFeat:
        - Feat #1
        - Feat #2
```

or @jcte02's clever proposal 
B)
```
tierX:
  Required:
    Feat:
    - Feat #1
    - Feat #2
  Optional:
    Feat:
    - Feat #3
    - Feat #4
```

This is powerful because it can as @jcte02 pointed out "allow us to code complex queries like the one for the Craft feat, which has the prerequisite of `Learning 3` attribute, OR `Knowledge I` feat."  

```
tier1:
  Optional:
    Feat:
    - Knowledge I
    Attribute:
    - Learning 3
```

If we don't do this now, then we'll send ourselves into a problem of combinatorial complexity with `n` combinations / permutations. Yes, it's true that this project isn't a true "program", but if we don't do this now, we will also need to do `FeatAttributeMulti` and `FeatAttributeSingle`.

LOL, obviously this was a huge architectural flaw and @jcte02's suggestion fixes it so we should fix it now rather than duct taping it over and over again until we're completely sunk.

**Comment by brianfeister** [comment]
And you're not the only one crying inside @ucffool ;(

**Comment by ucffool** [comment]
Well, if the structure does change (and I conceded @jcte02 solution is elegant and straight-forward), it'll be necessary to make the new .yml file under a different branch, to give @brianfeister time to prepare the new version of the parser for the main site while also affording myself and others a chance to do so as well before it goes live (so we can just merge in branches all at once so it looks seamless publicly and data isn't unavailable to folks for any period of time).

**Comment by jcte02** [comment]
@ucffool I am well aware that this means rewriting the application logic, but I think that it's not so bad for the following reasons:

1. The complexity of the parsing is reduced, since the logical relationships are now explicited and don't need to be inferred.
2. You can have an omogeneous system (so no headaches for special cases like `FeatAttribute`).
3. Once the migration is done, you don't need to update your parsing logic any more (since no more special keys are added).

**Comment by ucffool** [comment]
I've manually [fixed the feat](openlegend.heromuster.com/feats/multitargetboonexpert) for now.

**Comment by brianfeister** [comment]
@ucffool the only part I'm unclear on is whether you're directly consuming the YAML file from github or not? On my end, I parse it to JSON and this is exactly why I don't have automated builds set up for the openlegendrpg.com website, I can merge this change (preferable for preventing future merge conflicts) now and rebuild the `feats.yml` JSON that I use in my project at a deferred date after I change my application logic.

**Comment by ucffool** [comment]
I consume it only if it is changed, reading a local file either way, this way I didn't have to be actively involved in syncing it. I took the road which require less *pay attention to me* since it's a side project (and easy distraction from getting real-world work done). Of course that causes issues in this case, but I can easily uncomment 1 line of 1 file and stop the updates from occurring.

**Comment by jcte02** [comment]
Opened #278 to track this issue.

**Comment by brianfeister** [comment]
@ucffool - gotcha, you'll have to do that in this case. I just don't want to get merge conflicts and I actually prefer to git this in sooner than later to prevent poor souls like you, me, and the guy who made the React app from getting hit by this freight train 😂 

@jcte02 👍

**Comment by KevinBacas** [comment]
I'll follow both Issues. The commit in the merge request does not make any sens right now. Should I cloes it?

Tell me if I can help in any way 😄

**Comment by ucffool** [comment]
@brianfeister close.

**Pull request closed without merging**
