### PR TITLE
Typos in banes.yml

### PR DESCRIPTION
**Pull request by oconnor0**

### CODE REVIEW

**Comment by ucffool** [comment]
FYI, you can add multiple changes to a pull request (additional changes should automatically add themselves to a current pull request), just simplifies things.

**Comment by oconnor0** [comment]
Is there a way to do that in the GitHub UI?

**Comment by ucffool** [comment]
Yeah. Once you've created a Pull Request, simply make further changes and then push them up to GitHub. They will automatically be added on to any existing pull request ( a pull request is just a marker that says "Sync X from Y" and by pushing new things to your fork, the single pull request still holds true.

**Comment by brianfeister** [comment]
@oconnor0 Yes. You just browse the files normally at current master and then click `Edit [pencil icon]` and then go about editing. When you go to save the change, you just name your branch and then re-use the same branch name as your previous edit.

👍

**Comment by oconnor0** [comment]
I'll try to do that in the future. Thanks. :)

**Pull request merged**
