### PR TITLE
Standardization in Feats.YML

### PR DESCRIPTION
**Pull request by ucffool**
`any` before `and` has been the standard.

### CODE REVIEW

**Comment by brianfeister** [comment]
lol, no problem. Did I break your code boss?  Also, I reverted it, I think it must have been late, Defensive Master (for weapons with Defensive) really tends to be two-handed weapons in most cases so thematically it's dumb.

**Comment by ucffool** [comment]
Didn't break it per se, but it exposed a weakness in the design. On the upside, I noticed the difference in standardization 😃 It was showing as Agility4 or Defensive Mastery or Attack Specialization.

**Comment by jcte02** [comment]
@ucffool In theory the order shouldn't matter, because there is an implicit top level `and` key, and `1 && 2 = 2 && 1`. The `any` key is always on the top because it helped me while editing to visualize which feats I already converted.

**Comment by ucffool** [comment]
@jcte02 In theory correct, thus why i stated that it exposed a weakness in my processing. 
It's mainly because I try and increase readability by being explicit with using AND and OR. 

One of the UI _complaints_ on the main site is that the AND is suggested in the bulleted lists of prereqs, while within a bullet OR is explicit (grammatically) and AND is a [little wonky](http://www.openlegendrpg.com/feats/craft_mundane_item). I wanted to take out the assumptions and put AND and OR always, and `any` first helped make that easier to process.

**Comment by jcte02** [comment]
@ucffool whoops seems like I have misunderstood your message! I was thinking you found a design weakness in the yaml file 😄 . On the main site I agree that the prerequisite UI is kinda wonky, but I guess it's an easy fix.

**Comment by ucffool** [comment]
Well clearly it's not that easy (or I'm just not that smart) since that's what I'm trying to do on the HeroMuster page is make it easier to view. :)

**Comment by brianfeister** [comment]
LOL, would take me a few moments to add `AND`, I appreciate the usability help, but don't want the UI cluttered that way. For me, this communicates more clearly but results in an unattractive output in my opinion. 

image

**Comment by brianfeister** [comment]
The challenge is coming up with a visual representation for `AND` that is not an eye sore

**Comment by jcte02** [comment]
Yeah maybe it's not so easy after all

**Comment by ucffool** [comment]
Reminder: I came to this conclusion because **I** was confused by reading the main site's prereqs. Remember, sometimes it's hard to see things how a newbie to the system would see it (especially as the creator).

I would agree it's not the prettiest, but also agree that I couldn't come up with a better way to display it. Consider ALL of these variations:

feat prereqs

There is a lot of nuance in there and for someone new to the system (hell, sometimes even now) it's hard to wrap your head around it without being explicit (I made a lot of mistakes misreading feats early on).

**Comment by ucffool** [comment]
I'll also add that my #1 rule is to avoid the _wall of text_ problem, mainly because whenever I've written a webpage, especially a homepage, my personal tendency is to use too many words (I use to do that in improv as well), so I'm always trying to think of ways to reduce text on a page. 

Anyway, I'm going to reiterate that I'm not trying to be critical here, as the discussion was about standardization, just trying to share what my experience was like many months ago and what spurred me to even create the HeroMuster OL page.

**Comment by ucffool** [comment]
Here is what all those look like without the explicit **and**, just for comparison.
untitled2

**Comment by brianfeister** [comment]
@ucffool you're defending your design decision but I've already agreed with you. It's not the prettiest, but it communicates more clearly. We're on the same page, it just doesn't match up with my "minimum design quality" standard which is different for both of us. Also, it's good to have both your option `AND` mine, since the options are different and cover all bases.

**Comment by ucffool** [comment]
> Also, it's good to have both your option `AND` mine, since the options are different and cover all bases.
💯

**Comment by jcte02** [comment]
This may be going slightly off topic, but what sometimes confuses me is the list inside a list visual. I would prefer a table approach, so all different tier are squared out, and instead of bullet points, a single line for each item of the AND query. In the table header I would put something like "Required" to imply that the lines are linked in an AND query.

**Comment by brianfeister** [comment]
@jcte02 what would that table look like in markdown?

| Tier | Prereq  |
| :-:| :-: |
|  1 | Attack Specialization AND Agility 3, OR Might 3 |
|  2 | Attack Specialization AND Agility 4, OR Might 4 |

**Comment by ucffool** [comment]
I'll bite, in an effort to help.

| Tier | Feats | Attributes
| :-: | :-: | :-: |
|  1 | Attack Specialization | Agility 3, OR Might 3 |
|  2 | Attack Specialization | Agility 4, OR Might 4 |
````
| Tier | Feats | Attributes
| :-: | :-: | :-: |
|  1 | Attack Specialization | Agility 3, OR Might 3 |
|  2 | Attack Specialization | Agility 4, OR Might 4 |

**Comment by brianfeister** [comment]
@ucffool ok, I feel like there are 1 or 2 feats that allow:

```
any:
  Feat: 
  - Bane Focus
  Attribute:
  - Any Attribute 3
```

**Comment by jcte02** [comment]
@brianfeister yeah something similar but with a newline istead of AND.
@ucffool it has potential if we can figure out the special cases.

**Comment by brianfeister** [comment]
I like that idea @jcte02, though no idea when I would implement it given I'll have to redo all logic that outputs it

| Tier | Prereq  |
| :-:| :- |
|  1 | Attack Specialization <br>Agility 3, or Might 3 |
|  2 | Attack Specialization <br>Agility 4, or Might 4 |

**Comment by jcte02** [comment]
@brianfeister I have taken the liberty to inspect the site code and hack something together to hopefully ease your workload. 
**DISCLAMER** I do not know anything angularjs (but I dabble in js), so this may set the site on fire 🔥 . 
Anyway, here is the gist if you are interested: https://gist.github.com/jcte02/8f2914217e9923b86409fda765716377

**Comment by brianfeister** [comment]
Haha thanks @jcte02. I was thinking after my last comment I can probably do it with just CSS ;)

**Comment by jcte02** [comment]
Yeah I totally forgot that CSS even existed. It was a fun little side project for me though 😃

**Pull request merged**
