### PR TITLE
Update 01-chapter-one.md

### PR DESCRIPTION
**Pull request by Cryogenic6891**
I changed Drone from energy 4 to energy 3 to satisfy attribute sum of 20

Also dclasair contributed to these edits (in discord)

### CODE REVIEW

**Comment by istabosz** [comment]
Companion I gets 20 attribute points plus four per level, so that would be 24.

**Comment by brianfeister** [comment]
@Cryogenic6891 @istabosz thanks to both of you! @istabosz is right ... you want to update cam?

**Comment by brianfeister** [comment]
Great work, thanks @Cryogenic6891 and DCLaisar! ❤️ 💯 🎯

**Comment by Cryogenic6891** [comment]
oops, wonder why I decided that was wrong and manticore was fine, haha. Oh well, you're welcome!

**Pull request merged**
