### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by NinjaSudo**
@brianfeister @istabosz found these while I was pouring over the rules for character creation.

### CODE REVIEW

**Comment by raihje** [comment]
Energy resistance is in my fork and antoher pull request already, lol.
However, until Brian approves the style guideline I've used for feats I'm not issuing a pull request.

Nice catches though, I'm sure these will be put in.

**Comment by NinjaSudo** [comment]
@raihje yeah I've got a few other branches ready to PR, but decided to wait until more decisions were made: https://github.com/NinjaSudo/core-rules/branches

**Comment by raihje** [comment]
Yea I think they're waiting to resolve Alternate Form and add it. They've basically resolved the new defense but still haven't typed it out, perhaps they haven't settled on a name yet. There are a number of things on the cusp that I could probably implement and issue a PR but I'll wait and see if they end up doing it to avoid merge conflicts. These are fairly major changes and as much as I want to push development forward I'm not nearly in the position of editor. I can make a PR with my take on their changes but ultimately it's up to them.

**Comment by NinjaSudo** [comment]
agreed. I'm here to help, not hinder. When Brian gave the feedback that my
gender-specifics edit was a more major undertaking I realized he was right.

We'll see if I did a good enough job cleaning up the language w/ that
branch. ;)

Eddie

**Comment by brianfeister** [comment]
@NinjaSudo sorry for the merge conflict - pull upstream master into your branch and we'll get this in there

**Comment by NinjaSudo** [comment]
hmm having a few complications w/ github authentication and forks. I'll figure this out and submit the changes after fixing the conflicts.

**Comment by raihje** [comment]
If you have your fork local. Do this to force it to the upstream version (back up your repo first)
```
git reset --hard upstream/master
git push -f origin master
```
this will force your local workspace to look like the openlegend/upstream.
Then you can work in your fixes. Pushing with -f forces your remote repo to match openlegends, only do this if you've backed up your work. OR
```
git checkout upstream/master
git merge -s ours master
git mergetool
```
git mergetool will open (hopefully, I use gvim) a diff tool for you to compare, make necessary changes and save/resolve the conflict.

I do my work on branches of my master, which I hard reset to open legend before creating a branch to work on a specific thing. That way, there aren't any conflicts (hopefully) when it comes time to merge the PR.

**Comment by brianfeister** [comment]
These have been fixed by other changes. No longer valid. Closing.

**Pull request closed without merging**
